# Generated by Django 4.2.5 on 2023-09-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='длительность'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_path',
            field=models.FileField(upload_to='video/', verbose_name='ссылка на видео'),
        ),
    ]
