# Generated by Django 4.2.5 on 2023-09-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='date_last_viewing',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего просмотра'),
        ),
    ]
