# Generated by Django 4.2.5 on 2023-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_duration_alter_lesson_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='длительность'),
        ),
    ]
