# Generated by Django 4.2.5 on 2023-09-23 21:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lesson',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
